# Generated by Django 4.0.5 on 2022-07-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='languages',
            field=models.ManyToManyField(blank=True, to='main.skill'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_link',
            field=models.URLField(blank=True),
        ),
    ]
